spring:
  datasource:
    diver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project2?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ps4318
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /pic/**
  profiles:
    active: upload
server:
  port: 8081
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.groupten.project2.mapper: debug
mybatis:
  type-handlers-package: com.groupten.project2.typehandler
